### ISSUE TITLE
Use project board to organize meetings

### ISSUE THREAD

**Issue by slarge** [NOAA-EDAB/seaside#3]
@slucey @kimberly-bastille 
Maybe we can use the project board to coordinate topics/solicit pitches for seaside chats. That way we can create a backlog and come up with a meaningful development of topics from simple -> complex. Thoughts? 

Title: Continuous Integration for your package, book, or tests
Labels: "Topic"
Project: Seaside_Chats
Brief Description (with some discussion questions): Continuous Integration (CI) is often used for easily/frequently testing changes to a project/package/repository. RStudio recently highlighted that they have migrated their CI from Trav-s-CI to GitHub actions. 
* Where do you already use CI and why?
* What types of actions could we use? Where could we use them?
* Would it be worth the overhead to move from Travis-CI to GitHub Actions?
Lead: @slarge 
Time: 30 minutes
Resources:

**Comment by kimberly-bastille** [comment]
I like that idea. We could then move over our list of topic ideas and track our discussion topics linking to the notes so people can find them more easily if they want to go back.

**Comment by slucey** [comment]
Sounds good to me.

**Comment by kimberly-bastille** [comment]
@khyde Could you create an issue outlining what you would like to discuss for spatial-analysis using the template that Scott used for the continuous integration topic?

**Comment by slarge** [comment]
I created an issue template. Feel free to modify if there is more stuff you'd want to include.
