### ISSUE TITLE
New and improved survdat package

### ISSUE THREAD

**Issue by slucey** [NOAA-EDAB/seaside#30]
Lead: slucey

Brief Description: As part of the MS Keyrun project, @andybeet and @slucey have reconfigured the survdat package to make it more user friendly.  Now anyone can pull NEFSC bottom trawl data and calculate stratified means or swept-area biomass estimates.

Discussion topics: 
* How to install and run `survdat`
* Other features people would like to see implemented

Time: 30 min

Additional resources: [survdat package](https://github.com/NOAA-EDAB/survdat)

**Comment by kimberly-bastille** [comment]
The next open seaside chat is Jan 25th. Does this date work for you to share a rundown of survdat? @slucey

**Comment by slucey** [comment]
Sure.
